# Render 배포 설정
databases:
  - name: video-accounting-db
    databaseName: video_accounting
    user: video_user
    region: singapore  # Asia-Pacific region

services:
  - type: web
    name: video-accounting-backend
    env: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "./render_start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: video-accounting-db
          property: connectionString
      
      # Gmail SMTP 設定
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: "forone.video2@gmail.com"
      - key: SMTP_PASSWORD
        value: "ujqbdsagmerfbnvp"
      - key: FROM_EMAIL
        value: "forone.video2@gmail.com"
      
      # フロントエンドURL
      - key: FRONTEND_URL
        value: "https://video-accounting-app.vercel.app"
    autoDeploy: true